// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LandingPageWrapper': string;
  'NavBar': string;
  'buttonAnimation': string;
  'buttonDiv': string;
  'cube': string;
  'cubeAndShadow': string;
  'cubeAnimation': string;
  'cubeBox': string;
  'download': string;
  'invalidPage': string;
  'leftLandingPageWrapper': string;
  'logo': string;
  'rightLandingPageWrapper': string;
  'shadow': string;
  'shadowGrow': string;
  'stop': string;
}
export const cssExports: CssExports;
export default cssExports;
